### ISSUE TITLE
Technical guide on How to build a paid membership site with Stripe and SAWO

### ISSUE THREAD

**Issue by SawoCommunity** [Sawo-Community/Sawo-Docs#2]
We are seeking a technical guide on "How to build a paid membership site with Stripe and SAWO". Write according to the template as mentioned [here](https://github.com/Sawo-Community/Sawo-Docs/tree/main/Template-for-Guides). Try to be as creative as possible.

Strictly mention this issue, while submitting a Pull Request related to this issue. You can comment freely under this issue if you have any questions regarding the content. 

If you make a video tutorial walkthrough, make sure to include it in your markdown submission. Give a proper title and description to your PR.

**Comment by irsayvid** [comment]
Do we need to have a paid membership account in stripe to work on this issue?
