### ISSUE TITLE
Technical guide on How to implement Authentication in Next.js with SAWO

### ISSUE THREAD

**Issue by SawoCommunity** [Sawo-Community/Sawo-Docs#3]
We are seeking a technical guide on "How to implement Authentication in Next.js with SAWO". Write according to the template as mentioned [here](https://github.com/Sawo-Community/Docathon2022/blob/main/Resources/Template.md). Try to be as creative as possible.

Strictly mention this issue, while submitting a Pull Request related to this issue. You can comment freely under this issue if you have any questions regarding the content. 

If you make a video tutorial walkthrough, make sure to include it in your markdown submission. Give a proper title and description to your PR.

**Comment by shreya-gb** [comment]
Hello @SawoCommunity! As my PR wasn't visible on this repo. Sharing my Forked Link here. Thanks!

https://github.com/shreya-gb/Sawo-Docs/tree/main/NextJS

This document includes:

✅ What is NextJS? Who uses NextJS? & How can one get started with NextJS? 🎯
✅ The steps to integrate SAWO API with NextJS. 🎯
✅ Demonstrated authentication using the SAWO API key. 🎯
✅ Mentioned & Quoted the essential Packages. 🎯
✅ My PR follows the SAWO Documentation Template. 🎯
✅ Closes Issue #3
